languageCode = "en"
languageName = "english"
weight = 1
title = "Belajar Pintar"

[params]
  displayName = "english"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Situs Pendidikan Belajar Pintar"

[author]
  name = "Belajar Pintar"
  image = "img/blowfish_logo.png"
  headline = "Situs Pendidikan Belajar Pintar"
  bio = "Situs Pendidikan Belajar Pintar"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/rifabilek" },
  ]